language: generic
sudo: required

services:
        - docker

before_install:
        - docker build -t mpezzo/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true mpezzo/docker-react npm run test
